services:

  python312-web-backend-template-db:
    container_name: python312-web-backend-template-db
    image: postgres:latest
    environment:
      - 'POSTGRES_DB=${DB_DATABASE:-db_name}'
      - 'POSTGRES_USER=${DB_USERNAME:-username}'
      - 'POSTGRES_PASSWORD=${DB_PASSWORD:-password}'
    ports:
      - '${FORWARD_DB_PORT:-5432}:5432'
    volumes:
      - python312_web_backend_template_db_local:/var/lib/postgresql/data

  python312-web-backend-template:
    container_name: python312-web-backend-template
    depends_on:
      - python312-web-backend-template-db
    build:
      context: .
    ports:
      - '${BACKEND_PORT:-5000}:5000'
      - '${DEBUG_PORT:-5678}:5678'
    volumes:
      - '.:/app'
    environment:
      - 'APP_ENV=${APP_ENV:-development}'
      - 'BACKEND_PORT=${BACKEND_PORT:-5000}'
      - 'DEBUG_PORT=${DEBUG_PORT:-5678}'

volumes:
  python312_web_backend_template_db_local:
