"""add_middle

Revision ID: b7e00e42808b
Revises: 909b72ab8501
Create Date: 2024-09-16 20:44:05.285757

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b7e00e42808b'
down_revision: Union[str, None] = '909b72ab8501'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('middlename', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'middlename')
    # ### end Alembic commands ###
